name: bedtools_merge
description: combines overlapping or “book-ended” features in an interval file into a single feature which spans all of the combined features. Adapted from https://github.com/nf-core/modules/tree/fff2c3fc7cdcb81a2a37c3263b8ace9b353af407/modules/nf-core/bedtools
keywords:
  - bed
  - merge
  - bedtools
  - overlapped bed
tools:
  - bedtools:
      description: |
        A set of tools for genomic analysis tasks, specifically enabling genome arithmetic (merge, count, complement) on various file types.
      documentation: https://bedtools.readthedocs.io/en/latest/content/tools/merge.html
      licence: ["MIT"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - bed:
      type: file
      description: Input BED file
      pattern: "*.{bed}"
  - args:
      type: string
      description: optional arguments for bedtools merge
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - bed:
      type: file
      description: Overlapped bed file with combined features
      pattern: "*.{bed}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@kelly-sovacool"
maintainers:
  - "@kelly-sovacool"
